config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'home/top'
  get "/" => "home#top"
  devise_for :users
  resources :users
  resources :posts do
    collection do
      get 'search'
    end
  end
  resources :posts do
    resources :reservations, only: [:new, :create, :show]
  end 
  resources :reservations, only: [:confirm]  do 
    collection do
      post 'confirm'
    end
  end
  get "reservations/index" => "reservations#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image_name, ImageNameUploader
	has_many :reservations

	validates :name, presence: true
	validates :address, presence: true
	validates :introduce, presence: true
	validates :image_name, presence: true
	validates :price, presence: true
	
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :person, presence: true

 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations, dependent: :destroy
  mount_uploader :image_name, ImageNameUploader

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_search

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def set_search
    @search = Post.ransack(params[:q]) 
    @search_posts = @search.result
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @posts = Post.all.page(params[:page]).per(10)
    @reservations = Reservation.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "ルームを登録しました"
      redirect_to("/posts/#{@post.id}")
    else
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @reservation = Reservation.new
    @user = current_user
  end

  def search
    @posts = Post.all.page(params[:page]).per(10)
  end

  private
   
    def post_params
      params.require(:post).permit(:name, :introduce, :price, :address, :image_name)
    end

    def set_q
      @q = Post.ransack(params[:q])
    end
  
  

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @users = current_user
    @post = Post.find_by(id: params[:post_id])
    @reservation = Reservation.new
  end

  def confirm
    @users = current_user
    @post = Post.find_by(id: params[:post_id])
    @reservation = Reservation.new(params.permit(:id, :start_date, :end_date, :person, :post_id, :user_id))
    if (@reservation.start_date < Date.today) || (@reservation.end_date < Date.today)
      flash[:notice] = "今日以降の日付をチェックしてください"
      render :new
    end
    @reservation.total_days = (@reservation.end_date - @reservation.start_date).to_i
    if @reservation.total_days <= 0
      flash[:notice] = "チェックインはチェックアウトより前にしてください"
      render :new
    end
    @reservation.total_price = (@reservation.total_days * @reservation.person * @post.price).to_i
  end

  def create
    @user = current_user
    @post = Post.find_by(id: params[:post_id])
    @reservation = Reservation.new(params.permit(:start_date, :end_date, :person, :total_days, :total_price, :post_id, :user_id))
    @reservation.user_id = @user.id
    @reservation.name = @post.name
    @reservation.image_name = @post.image_name
    @reservation.introduce = @post.introduce
    if @reservation.save!
      flash[:notice] = "予約を完了しました"
      redirect_to "/posts/#{@reservation.post_id}/reservations/#{@reservation.id}"
    else
      render :confirm
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @post = Post.find_by(id: params[:post_id])
  end

  def index
    @reservations = Reservation.all
    @posts = Post.all
    
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(params.require(:user).permit(:image_name, :name, :text))
      flash[:notice] = "プロフィールを更新しました"
      redirect_to :user
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="main-container">
	<div class="first-view">
		<div class="submit-form">
			<div class="form-area">
				<p>Potepan Shareでまだ体験したことのない旅をしよう</p>
				<dl class="searchbox">
					<%= search_form_for @search, url: search_posts_path do |f| %>
						<dt><%= f.text_field :address_cont ,placeholder: 'エリア' %></dt>
						<dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
					<% end %>
				</dl>
			</div>
		</div>
	</div>
</div>

<div class="second-container">
  <div class="topic-title">
	  <h1>おすすめのエリア</h1>
	</div>
	<div class='topic-image'>
    <ul class="pictures">
      <li class="list"><%= image_tag "tokyo.jpg" %></li>
      <li class="list"> <%= image_tag "osaka.jpg" %></li>
      <li class="list"><%= image_tag "kyoto.jpg" %></li>
      <li class="list"> <%= image_tag "sapporo.jpg" %></li>
    </ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <header>
      <div class="header">
        <ul class="header-left">
          <li>
            <%= link_to image_tag("header_logo.png"), "/" %>
          </li>
          <li>
            <dl class="searchbox">
              <%= search_form_for @search, url: search_posts_path do |f| %>
                <dt><%= f.text_field :address_cont ,placeholder: 'エリア' %></dt>
                <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
              <% end %>
            </dl>
          </li>
          <li>
            <dl class="searchbox">
              <%= search_form_for @search, url: search_posts_path do |f| %>
                <dt><%= f.text_field :name_or_introduce_or_address_cont ,placeholder: 'キーワード' %></dt>
                <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
              <% end %>
            </dl>
          </li>
        </ul>
          <nav>
            <% if user_signed_in? %>
              <ul class="header-menu">
                <li class="header-menu_item"><%= current_user.name %></li>
                <li class="header-menu_item">
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fa-solid fa-bars"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">
                      <button class="dropdown-item" type="button"><%= link_to "ルーム登録", new_post_path %></button>
                      <button class="dropdown-item" type="button"><%= link_to "予約済みルーム一覧", reservations_index_path %></button>
                      <button class="dropdown-item" type="button"><%= link_to "登録済みルーム一覧", posts_path %></button>
                      <button class="dropdown-item" type="button"><%= link_to "設定", edit_user_path(current_user) %></button>
                      <button class="dropdown-item" type="button"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></button>
                    </div>
                  </div>
                </li>
              </ul>
            <% else %>
              <ul class="header-menu">
                <li class="header-menu_item"><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
                <li class="header-menu_item"><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
              </ul>
            <% end %>
          </nav>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <footer class="footer">
      <p>© 2020 POTEPAN.INC</p>
    </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container-index">
	<h4>登録済みルーム一覧</h4>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ルーム画像</th>
				<th>ルーム名</th>
				<th>ルーム紹介</th>
				<th>料金</th>
				<th>作成日</th>
			</tr>
		</thead>
			<% @posts.each do |post| %>
				<tbody>
					<tr class="registered">
						<td><%= image_tag "#{post.image_name}", size: '240x140' %></td>
						<td><%= link_to post.name, post_path(post) %></td>
						<td><%= post.introduce%></td>
						<td>¥<%= post.price %></td>
						<td><%= post.created_at %></td>
					</tr>
				</tbody>
			<% end %>
	</table>
	<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="contaner">
	
	<div class="sidebar">
			<ul>
				<li><%= link_to "基本情報",	new_post_path %></li>
			</ul>
	</div>

	<div class="body">
		<% @post.errors.full_messages.each do |message| %>
        <div class="errors_message">
        <%= message %>
        </div>
    <% end %>

		<%= form_with model: @post do |f| %>

		<div class="card" style="width: 54rem;">
  		<div class="card-header">ルーム情報登録</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<label for="name">ルーム名</label><%= f.text_field :name, placeholder: "ルーム名を入力" %>
				</li>
				<li class="list-group-item">
					<label for="introduce">ルーム紹介</label><%= f.text_area :introduce, placeholder: "ルーム説明を入力" %>
				</li>
				<li class="list-group-item">
					<label for="price">料金</label><%= f.text_field :price, placeholder: "1日あたりの料金を入力" %>
				</li>
				<li class="list-group-item">
					<label for="address">住所</label><%= f.text_field :address, placeholder: "住所を入力" %>
				</li>
				<li class="list-group-item">
					<label for="image_name">ルーム画像</label><%= f.file_field :image_name, placeholder: "ファイルを選択　" %>
				</li>
				<li class="list-group-item">
					<input type="submit" value="登録" class="btn btn-sm btn-danger">
				</li>
			</ul>
		</div>

		<% end %>

</div>

app/views/posts/search.html.erb
<div class="container-index">
	<h4>検索結果:<%= @search_posts.count %>件</h4>
	<div class="search">
	<table class="table table-striped" style="width: 800px;">
		<thead>
			<tr>
				<th>ルーム画像</th>
				<th>ルーム名</th>
				<th>ルーム紹介</th>
				<th>料金</th>
				<th>作成日</th>
			</tr>
		</thead>
			<% @search_posts.each do |post| %>
				<tbody>
					<tr class="registered">
						<td><%= image_tag "#{post.image_name}", size: '240x140' %></td>
						<td><%= link_to post.name, post_path(post) %></td>
						<td><%= post.introduce%></td>
						<td>¥<%= post.price %></td>
						<td><%= post.created_at %></td>
					</tr>
				</tbody>
			<% end %>
	</table>
	</div>
	<%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="container">

	<div class="image-bar">
		<div class="card" style="width: 70rem;">
			<%= image_tag "#{@post.image_name}" %>
			<div class="card-body">
				<h5 class="card-title"><%= @post.name %></h5>
				<p class="card-text"><%= @post.introduce %></p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item"><%= @post.address %></li>
			</ul>
			 <div class="card-body">
				<%= form_with url: new_post_reservation_path(@post), method: :get, local: true do |f| %>
					<%= f.hidden_field :post_id, value: @post.id %>
					<%= f.submit "予約画面へ", class: "btn btn-sm btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>

</div>

app/views/reservations/confirm.html.erb
<div class="card" style="width: 54rem;">
	<div class="card-header">予約内容確認</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			<label for="name">料金</label>¥<%= @post.price %> /日
		</li>
		<li class="list-group-item">
			<label for="name">チェックイン</label><%= @reservation.start_date %>
		</li>
		<li class="list-group-item">
			<label for="name">チェックアウト</label><%= @reservation.end_date %>
		</li>
		<li class="list-group-item">
			<label for="name">宿泊日数</label><%= @reservation.total_days %>
		</li>
		<li class="list-group-item">
			<label for="name">人数</label><%= @reservation.person %>
		</li>
		<li class="list-group-item">
			<label for="name">合計金額</label>¥<%= @reservation.total_price %>
		</li>
		<div class="card-body">
			<%= link_to "ルーム詳細に戻る", "/posts/#{@post.id}" , class: "btn btn-danger" %>
		</div>
		<div class="card-body">
			<%= form_with url: post_reservations_path(@post) do |f| %>
				<%= f.hidden_field :start_date, value: @reservation.start_date %>
				<%= f.hidden_field :end_date, value: @reservation.end_date %>
				<%= f.hidden_field :total_days, value: @reservation.total_days %>
				<%= f.hidden_field :person, value: @reservation.person %>
				<%= f.hidden_field :total_price, value: @reservation.total_price %>
				<%= f.hidden_field :post_id %>
				<%= f.submit "予約を確定する", class:"btn btn-primary" %>
			<% end %>
		</div>
	</ul>
</div>

app/views/reservations/index.html.erb
<h4>予約済みルーム一覧</h4>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ルーム画像</th>
      <th scope="col">ルーム名</th>
      <th scope="col">ルーム紹介</th>
      <th scope="col">合計金額</th>
			<th scope="col">チェックイン</th>
			<th scope="col">チェックアウト</th>
			<th scope="col">予約確定日時</th>
    </tr>
  </thead>
	<% @reservations.each do |reservation| %>
  <tbody>
    <tr>
      <td><%= image_tag "#{reservation.image_name}", size: '240x140' %></td>
      <td><%= link_to reservation.name, post_path(reservation) %></td>
      <td><%= reservation.introduce %></td>
			<td>¥<%= reservation.total_price %></td>
			<td><%= reservation.start_date %></td>
			<td><%= reservation.end_date %></td>
			<td><%= reservation.created_at %></td>
    </tr>
  </tbody>
	<% end %>
</table>

app/views/reservations/new.html.erb
<%= form_with url: confirm_reservations_path do |f| %>
	<div class="card" style="width: 54rem;">
		<div class="card-header">
			予約画面
		</div>
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<label for="name">料金</label>¥<%= @post.price %> /日
			</li>
			<li class="list-group-item">
				<label for="introduce">チェックイン</label><%= f.date_field :start_date %>
			</li>
			<li class="list-group-item">
				<label for="price">チェックアウト</label><%= f.date_field :end_date %>
			</li>
			<li class="list-group-item">
				<label for="address">人数</label><%= f.number_field :person %>
			</li>
			<li class="list-group-item">
				<%= f.submit "確認画面へ", class: "btn btn-sm btn-primary" %>
			</li>
		</ul>
	</div>
	<%= f.hidden_field :post_id, value: @post.id %>
<% end %>

app/views/reservations/show.html.erb
<div class="card" style="width: 54rem;">
	<div class="card-header">予約詳細画面</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			<label for="name">予約した部屋</label><%= @post.name %>
		</li>
		<li class="list-group-item">
			<label for="introduce">チェックイン</label><%= @reservation.start_date %>
		</li>
		<li class="list-group-item">
			<label for="price">チェックアウト</label><%= @reservation.end_date %>
		</li>
		<li class="list-group-item">
			<label for="address">価格</label><%= @reservation.total_price %>円
		</li>
	</ul>
</div>

app/views/users/edit.html.erb
<div class="contaner">
	
	<div class="sidebar">
		<p><%= current_user.name %></p>
			<ul>
				<li><%= link_to "アカウント", user_path(current_user) %></li>
				<li><%= link_to "プロフィール", edit_user_path(current_user) %></li>
			</ul>
	</div>
	
	<div class="body">
		<% @user.errors.full_messages.each do |message| %>
        <div class="errors_message">
        <%= message %>
        </div>
    <% end %>

		<%= form_with model: @user do |f| %>
		
		<div class="card" style="width: 54rem;">
  		<div class="card-header">プロフィール</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<%= image_tag "#{@user.image_name}", class:"icon" %>
				</li>
				<li class="list-group-item">
					<label for="email">アイコン画像</label><%= f.file_field :image_name, placeholder: "画像を選択" %>
				</li>
				<li class="list-group-item">
					<label for="email">名前</label><%= f.text_field :name, placeholder: current_user.name %>
				</li>
				<li class="list-group-item">
					<label for="password">自己紹介文</label><%= f.text_area :text, placeholder: "自己紹介を入力" %>
				</li>
				<li class="list-group-item">
					<input type="submit" value="更新" class="btn btn-sm btn-danger">
				</li>
			</ul>
		</div>
		
		<% end %>
	
	</div>

</div>		

app/views/users/show.html.erb
<div class="contaner">
	
	<div class="sidebar">
		<p><%= current_user.name %></p>
			<ul>
				<li><%= link_to "アカウント", user_path(current_user) %></li>
				<li><%= link_to "プロフィール", edit_user_path(current_user) %></li>
			</ul>
	</div>
	
	<div class="body">
		<div class="card" style="width: 54rem;">
  		<div class="card-header">
    	アカウント
  		</div>
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<label for="email">メールアドレス</label><%= @user.email %>
			</li>
			<li class="list-group-item">
				<label for="password">パスワード</label><%= "*********" %>
			</li>
			<li class="list-group-item">
				<%= link_to "編集", edit_user_registration_path, class: "btn btn-sm btn-danger" %>
			</li>
		</ul>
		</div>
	</div>

</div>		